updated

diff --git a/work_timer b/work_timer
--- a/work_timer
+++ b/work_timer
@@ -1,7 +1,44 @@
+# Created by Najeeb A. on  01/09/2021
+# Copyright © 2021 Najeeb A. All rights reserved.
+
 #!/bin/bash
 
 # Comment out line 5 and uncomment line 4 if there are problems with the alarm sound
 
 #DIR=$(zenity --file-selection)
 DIR=~/terminal_work_timer
-cd $DIR & xfce4-terminal --geometry=20x10 --hide-scrollbar --hide-menubar --title="Work Timer" -e "sh -c $DIR/terminal_work_timer"
+
+if ! (dpkg -s xfce4-terminal >/dev/null 2>&1) && ! (rpm -q xfce4-terminal >/dev/null 2>&1) && ! (yum list installed xfce4-terminal >/dev/null 2>&1) && ! (dnf list installed xfce4-terminal >/dev/null 2>&1) && ! (which hub >/dev/null 2>&1)
+then
+	echo -n "xfce4-terminal is not found! Do you want to install it? (Y/n): "
+	read answer
+	echo -ne "\033[A\033[2K\r"
+	if [[ $answer == 'Y' || $answer == 'y' ]] 
+	then
+		if (sudo apt-get -y install xfce4-terminal >/dev/null 2>&1) ;
+		then
+			echo "Finished Downloading xfce4-terminal"
+			sleep 1 && echo -ne "\033[A\033[2K\r\033[A\033[2K\r"
+		# it works the same as the previous if condition just different format
+		elif (yes | sudo pacman -S xfce4-terminal >/dev/null 2>&1) ;
+		then
+			echo "Finished Downloading xfce4-terminal"
+			sleep 1 && echo -ne "\033[A\033[2K\r\033[A\033[2K\r"
+		# it works the same as the "if ! dpkg" condition just different format 
+		elif ! (sudo yum -y install xfce4-terminal >/dev/null 2>&1) ;
+		then
+			echo "Couldn't install it, you need to install it manually"
+			echo "Error, Program exit"
+			sleep 2 && echo -ne "\033[A\033[2K\r\033[A\033[2K\r\033[A\033[2K\r"			
+			exit 1
+
+		fi
+	else
+		echo "xfce4-terminal is dependency for the program to work, Program Exit!"
+		echo "--- Unsuccessful ---"
+		sleep 2 && echo -ne "\033[A\033[2K\r\033[A\033[2K\r\033[A\033[2K\r"		
+		exit 1
+	fi
+else
+	cd $DIR & xfce4-terminal --geometry=20x10 --hide-scrollbar --hide-menubar --title="Work Timer" -e "sh -c $DIR/terminal_work_timer"
+fi
